import { shareDocumentText } from "@/lib/docgen/shareDocument";
import type { BusinessProfile } from "@/lib/supabase/hooks/useBusinessProfile";

// A report is a screenful of computed numbers, not a stored document, so there's
// no HTML to archive — just a clean plain-text summary the owner can paste into
// WhatsApp/email or print. Built on the same shareDocumentText primitive the
// invoice/statement flows use (navigator.share, clipboard fallback).
export async function shareReport(
  title: string,
  subtitle: string,
  lines: string[],
  business: BusinessProfile | null | undefined
) {
  const header = business?.name?.trim() || "Worklog";
  const text = [
    header,
    title,
    subtitle,
    ``,
    ...lines,
    ``,
    `Tip: open in a browser and Print → Save as PDF.`,
    `Generated by Worklog`,
  ].join("\n");
  await shareDocumentText(title, text);
}
