"use client";

import { useState } from "react";
import Link from "next/link";
import { useInvoices } from "@/lib/supabase/hooks/useInvoices";
import { useContacts } from "@/lib/supabase/hooks/useContacts";
import { useBusinessProfile } from "@/lib/supabase/hooks/useBusinessProfile";
import { Field } from "@/components/ui/Field";
import { Input } from "@/components/ui/Input";
import { buildStatementHTML, type StatementLine } from "@/lib/docgen/buildLedgerHTML";
import { openDocumentForPrinting, shareDocumentText } from "@/lib/docgen/shareDocument";
import { fmt } from "@/lib/format";

export function StatementView() {
  const { data: invoices } = useInvoices();
  const { data: contacts } = useContacts();
  const { data: business } = useBusinessProfile();

  const [selectedClient, setSelectedClient] = useState("");
  const [showPicker, setShowPicker] = useState(false);

  const clientNames = [
    ...new Set([
      ...(contacts ?? []).filter((c) => c.contact_type === "client").map((c) => c.name),
      ...(invoices ?? []).map((i) => i.client_name),
    ]),
  ]
    .filter(Boolean)
    .sort();

  const clientInvoices = (invoices ?? [])
    .filter((i) => i.client_name === selectedClient)
    .sort((a, b) => a.issue_date.localeCompare(b.issue_date));

  const totalInvoiced = clientInvoices.reduce((s, i) => s + Number(i.invoice_amount) + Number(i.vat_amount ?? 0), 0);
  const totalOutstanding = clientInvoices
    .filter((i) => i.status !== "paid")
    .reduce((s, i) => s + Number(i.balance_due) + Number(i.vat_amount ?? 0), 0);
  const totalReceived = totalInvoiced - totalOutstanding;

  const asAt = new Date().toLocaleDateString("en-ZA", { year: "numeric", month: "long", day: "numeric" });

  const owedFor = (name: string) =>
    (invoices ?? [])
      .filter((i) => i.client_name === name && i.status !== "paid")
      .reduce((s, i) => s + Number(i.balance_due) + Number(i.vat_amount ?? 0), 0);

  const handlePrint = () => {
    if (!business) return;
    const lines: StatementLine[] = clientInvoices.map((i) => ({
      date: i.issue_date,
      reference: i.doc_number,
      amount: Number(i.invoice_amount) + Number(i.vat_amount ?? 0),
      balance: Number(i.balance_due) + Number(i.vat_amount ?? 0),
      paid: i.status === "paid",
    }));
    const html = buildStatementHTML(
      business,
      selectedClient,
      lines,
      { invoiced: totalInvoiced, received: totalReceived, outstanding: totalOutstanding },
      asAt
    );
    openDocumentForPrinting(html, `statement-${selectedClient.replace(/\s+/g, "-")}`);
  };

  const handleShare = async () => {
    const text = [
      `ACCOUNT STATEMENT — ${selectedClient}`,
      `As at ${asAt}`,
      ``,
      `Total invoiced: ${fmt(totalInvoiced)}`,
      `Total received: ${fmt(totalReceived)}`,
      `Balance outstanding: ${fmt(totalOutstanding)}`,
      ``,
      `Generated by WORKLOG`,
    ].join("\n");
    await shareDocumentText(`Statement — ${selectedClient}`, text);
  };

  return (
    <div style={{ padding: "20px 16px 100px" }}>
      <Link href="/dashboard" style={{ fontSize: 12, color: "#64748b" }}>
        ← Dashboard
      </Link>
      <h1 style={{ fontSize: 20, fontWeight: 800, color: "#1B4332", margin: "4px 0 18px" }}>Customer Statement</h1>

      <div style={{ background: "#F0F9FF", border: "1.5px solid #7DD3FC", borderRadius: 12, padding: "12px 14px", marginBottom: 18, fontSize: 12, color: "#0369A1", lineHeight: 1.5 }}>
        A statement shows a customer their full account history — all invoices issued and what they still owe. Share it to resolve disputes or as a payment reminder.
      </div>

      <Field label="Select customer">
        <div style={{ position: "relative" }}>
          <Input value={selectedClient} onChange={setSelectedClient} placeholder="Type name or tap List..." />
          {clientNames.length > 0 && (
            <button
              onClick={() => setShowPicker((p) => !p)}
              style={{ position: "absolute", right: 10, top: "50%", transform: "translateY(-50%)", background: "#0C4A6E", border: "none", borderRadius: 8, padding: "5px 10px", color: "#fff", fontSize: 12, fontWeight: 700, cursor: "pointer" }}
            >
              {showPicker ? "✕" : "👤 List"}
            </button>
          )}
        </div>
        {showPicker && (
          <div style={{ background: "#fff", border: "1.5px solid #BAE6FD", borderRadius: 12, marginTop: 6, overflow: "hidden", maxHeight: 200, overflowY: "auto", boxShadow: "0 4px 12px rgba(0,0,0,0.1)" }}>
            {clientNames.map((n) => {
              const owed = owedFor(n);
              return (
                <button
                  key={n}
                  onClick={() => {
                    setSelectedClient(n);
                    setShowPicker(false);
                  }}
                  style={{ width: "100%", padding: "11px 14px", border: "none", borderBottom: "1px solid #F0F9FF", background: "#fff", cursor: "pointer", textAlign: "left", display: "flex", justifyContent: "space-between", alignItems: "center" }}
                >
                  <span style={{ fontSize: 14, fontWeight: 700, color: "#111" }}>{n}</span>
                  {owed > 0 && <span style={{ fontSize: 11, fontWeight: 700, color: "#b45309", background: "#fff7ed", padding: "3px 8px", borderRadius: 10 }}>{fmt(owed)} owed</span>}
                </button>
              );
            })}
          </div>
        )}
      </Field>

      {selectedClient && clientInvoices.length === 0 && (
        <div style={{ background: "#f8fafc", borderRadius: 12, padding: "14px 16px", textAlign: "center", color: "#94a3b8", fontSize: 13 }}>
          No invoices found for {selectedClient}
        </div>
      )}

      {selectedClient && clientInvoices.length > 0 && (
        <>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 10, marginBottom: 16 }}>
            {[
              { label: "Total invoiced", value: fmt(totalInvoiced), color: "#0C4A6E" },
              { label: "Received", value: fmt(totalReceived), color: "#0369A1" },
              { label: "Outstanding", value: fmt(totalOutstanding), color: totalOutstanding > 0 ? "#b45309" : "#0C4A6E" },
            ].map((s) => (
              <div key={s.label} style={{ background: "#f8fafc", borderRadius: 12, padding: "12px 10px", textAlign: "center" }}>
                <div style={{ fontSize: 10, color: "#64748b", fontWeight: 700, textTransform: "uppercase", marginBottom: 4 }}>{s.label}</div>
                <div style={{ fontSize: 14, fontWeight: 800, color: s.color }}>{s.value}</div>
              </div>
            ))}
          </div>

          {clientInvoices.map((inv) => {
            const paid = inv.status === "paid";
            const total = Number(inv.invoice_amount) + Number(inv.vat_amount ?? 0);
            const balance = Number(inv.balance_due) + Number(inv.vat_amount ?? 0);
            return (
              <div key={inv.id} style={{ background: paid ? "#F0F9FF" : "#fff7ed", borderRadius: 12, padding: "11px 14px", marginBottom: 8, display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                <div>
                  <div style={{ fontSize: 13, fontWeight: 700, color: "#111" }}>{inv.doc_number}</div>
                  <div style={{ fontSize: 11, color: "#94a3b8" }}>
                    {inv.issue_date}
                    {inv.due_date ? ` · Due ${inv.due_date}` : ""}
                  </div>
                </div>
                <div style={{ fontSize: 14, fontWeight: 800, color: paid ? "#0369A1" : "#b45309" }}>
                  {paid ? `✓ ${fmt(total)}` : `${fmt(balance)} due`}
                </div>
              </div>
            );
          })}

          <div style={{ display: "flex", gap: 10, marginTop: 16 }}>
            <button
              onClick={handlePrint}
              disabled={!business}
              style={{ flex: 1, background: "#f0fdf4", color: "#1B4332", border: "1.5px solid #d1fae5", borderRadius: 12, padding: 13, fontWeight: 700, fontSize: 13, cursor: "pointer" }}
            >
              🖨️ Save as PDF / Print
            </button>
            <button
              onClick={handleShare}
              style={{ flex: 1, background: "#f0fdf4", color: "#1B4332", border: "1.5px solid #d1fae5", borderRadius: 12, padding: 13, fontWeight: 700, fontSize: 13, cursor: "pointer" }}
            >
              📤 Share
            </button>
          </div>
        </>
      )}
    </div>
  );
}
